CREATE TABLE "equipment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "equipment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"order_number" text NOT NULL,
	"invoice_number" text,
	"customer_name" text NOT NULL,
	"customer_phone" text DEFAULT '' NOT NULL,
	"customer_email" text DEFAULT '' NOT NULL,
	"equipment_type" text NOT NULL,
	"assigned_technician" text DEFAULT 'Sin asignar' NOT NULL,
	"brand" text DEFAULT '' NOT NULL,
	"model" text DEFAULT '' NOT NULL,
	"serial_number" text DEFAULT '' NOT NULL,
	"accessories" text DEFAULT '' NOT NULL,
	"reported_issue" text NOT NULL,
	"diagnosis" text DEFAULT '' NOT NULL,
	"damage_notes" text DEFAULT '' NOT NULL,
	"parts_description" text DEFAULT '' NOT NULL,
	"parts_cost_cents" integer DEFAULT 0 NOT NULL,
	"labor_description" text DEFAULT 'Servicio técnico / mano de obra' NOT NULL,
	"labor_cost_cents" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'ingreso' NOT NULL,
	"entry_date" text NOT NULL,
	"exit_date" text,
	"invoice_subtotal_cents" integer,
	"invoice_tax_cents" integer,
	"invoice_total_cents" integer,
	"invoice_tax_rate" double precision,
	"warranty_days" integer DEFAULT 30 NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "equipment_order_number_unique" UNIQUE("order_number"),
	CONSTRAINT "equipment_invoice_number_unique" UNIQUE("invoice_number")
);
--> statement-breakpoint
CREATE INDEX "idx_equipment_updated_at_id" ON "equipment" USING btree ("updated_at","id");--> statement-breakpoint
CREATE INDEX "idx_equipment_status" ON "equipment" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_equipment_exit_date" ON "equipment" USING btree ("exit_date");--> statement-breakpoint
CREATE INDEX "idx_equipment_status_entry_date" ON "equipment" USING btree ("status","entry_date");--> statement-breakpoint
CREATE INDEX "idx_equipment_customer_name" ON "equipment" USING btree ("customer_name");