CREATE TABLE "payments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"operation_id" text NOT NULL UNIQUE,
	"equipment_id" integer NOT NULL,
	"amount_cents" integer NOT NULL,
	"method" text NOT NULL,
	"reference" text DEFAULT '' NOT NULL,
	"note" text NOT NULL,
	"reversal_of" integer UNIQUE,
	"actor_user_id" text NOT NULL,
	"actor_email" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payment_sign" CHECK (("amount_cents" > 0 AND "reversal_of" IS NULL) OR ("amount_cents" < 0 AND "reversal_of" IS NOT NULL))
);
--> statement-breakpoint
ALTER TABLE "equipment" ADD COLUMN "paid_cents" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_payments_equipment" ON "payments" ("equipment_id","id");--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_equipment_id_equipment_id_fkey" FOREIGN KEY ("equipment_id") REFERENCES "equipment"("id");--> statement-breakpoint
ALTER TABLE "equipment" ADD CONSTRAINT "equipment_paid_nonnegative" CHECK ("paid_cents" >= 0);