"use client";
import { useEffect,useState } from "react";
import { useModal } from "./use-modal";
import { inventoryRequest } from "./inventory-client";
import { formatDate } from "../lib/totals";
type OpenOrder={id:number;version:number;orderNumber:string;equipmentType:string;brand:string;model:string;reportedIssue:string;entryDate:string;assignedTechnician:string};
type Page={equipment:OpenOrder[];nextCursor:string|null;total:number};
export function OpenOrders({canClaim,onClose,onTaken}:{canClaim:boolean;onClose:()=>void;onTaken:()=>void}){
  const [page,setPage]=useState<Page|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState<number|null>(null),[error,setError]=useState(""),[refresh,setRefresh]=useState(0);
  const close=()=>{if(busy===null)onClose();};const ref=useModal(close);
  useEffect(()=>{const controller=new AbortController();void(async()=>{await Promise.resolve();if(controller.signal.aborted)return;setLoading(true);try{const result=await inventoryRequest<Page>("/api/equipment?view=available&limit=50",{signal:controller.signal});if(!controller.signal.aborted)setPage(result);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"No se pudieron cargar las órdenes.");}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();},[refresh]);
  async function take(order:OpenOrder){if(busy!==null)return;setBusy(order.id);setError("");try{await inventoryRequest("/api/equipment/claim",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:order.id,version:order.version})});onTaken();}catch(e){setError(e instanceof Error?e.message:"No se pudo tomar la orden.");setRefresh(v=>v+1);}finally{setBusy(null);}}
  async function more(){if(!page?.nextCursor||loading)return;setLoading(true);try{const next=await inventoryRequest<Page>(`/api/equipment?view=available&limit=50&cursor=${encodeURIComponent(page.nextCursor)}`);setPage({...next,equipment:[...page.equipment,...next.equipment]});}catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar las órdenes.");}finally{setLoading(false);}}
  return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section ref={ref} className="drawer detail-drawer" role="dialog" aria-modal="true" aria-labelledby="open-orders-title"><div className="drawer-head"><h2 id="open-orders-title">Órdenes abiertas</h2><button className="close" onClick={close} disabled={busy!==null} aria-label="Cerrar">×</button></div><div className="detail-body"><p>{canClaim?"Selecciona el trabajo que vas a realizar. Al tomarlo aparecerá en Mis órdenes, en reparación.":"Estas órdenes están disponibles para que un técnico las tome."}</p><button className="secondary-button" disabled={loading||busy!==null} onClick={()=>setRefresh(v=>v+1)}>Actualizar</button>{error&&<p className="field-error" role="alert">{error}</p>}{loading&&<p role="status">Cargando órdenes…</p>}{!loading&&!page?.equipment.length&&<p>No hay órdenes disponibles.</p>}<ul className="open-orders-list">{page?.equipment.map(order=><li key={order.id}><div><strong>{order.orderNumber} · {[order.equipmentType,order.brand,order.model].filter(Boolean).join(" ")}</strong><p>{order.reportedIssue}</p><small>Ingreso: {formatDate(order.entryDate)}{order.assignedTechnician!=="Sin asignar"?` · Reservada para ${order.assignedTechnician}`:""}</small></div>{canClaim&&<button className="primary-button" disabled={busy!==null} onClick={()=>void take(order)}>{busy===order.id?"Asignando…":"Tomar orden"}</button>}</li>)}</ul>{page?.nextCursor&&<button className="secondary-button" disabled={loading||busy!==null} onClick={()=>void more()}>Cargar más</button>}</div></section></div>;
}
