"use client";
import { useEffect,useState } from "react";
import { useModal } from "./use-modal";
import { useUnsavedChanges,confirmDiscardChanges } from "./use-unsaved-changes";
import { inventoryRequest } from "./inventory-client";
import { roleLabels,type Role } from "../lib/permissions";
import type { Staff } from "../lib/staff";
type Page={users:Staff[];nextCursor:number|null;audit:{id:number;message:string;actorEmail:string;createdAt:string}[]};
export function UsersPanel({memberId,onClose,onChanged}:{memberId:number;onClose:()=>void;onChanged:()=>void}){
  const empty={email:"",name:"",role:"lectura" as Role,enabled:1};
  const [page,setPage]=useState<Page|null>(null),[selected,setSelected]=useState<Staff|null>(null),[form,setForm]=useState(empty),[baseline,setBaseline]=useState(empty),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[refresh,setRefresh]=useState(0);
  const dirty=JSON.stringify(form)!==JSON.stringify(baseline);useUnsavedChanges(dirty||busy);
  const close=()=>{if(!busy&&(!dirty||confirmDiscardChanges()))onClose();};const ref=useModal(close);
  useEffect(()=>{const controller=new AbortController();void(async()=>{await Promise.resolve();if(controller.signal.aborted)return;setLoading(true);try{const result=await inventoryRequest<Page>("/api/users",{signal:controller.signal});if(!controller.signal.aborted)setPage(result);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"No se pudieron cargar los usuarios.");}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();},[refresh]);
  function choose(user:Staff|null){if(busy||(dirty&&!confirmDiscardChanges()))return;const values=user?{email:user.email,name:user.name,role:user.role,enabled:user.enabled}:empty;setSelected(user);setForm(values);setBaseline(values);setError("");}
  async function save(event:React.FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError("");try{const result=await inventoryRequest<{user:Staff}>("/api/users",{method:selected?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,id:selected?.id,version:selected?.version})});setSelected(result.user);const next={email:result.user.email,name:result.user.name,role:result.user.role,enabled:result.user.enabled};setForm(next);setBaseline(next);setRefresh(v=>v+1);onChanged();}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar la cuenta.");}finally{setBusy(false);}}
  async function more(){if(!page?.nextCursor||loading)return;setLoading(true);try{const next=await inventoryRequest<Page>(`/api/users?before=${page.nextCursor}`);setPage({...next,users:[...page.users,...next.users]});}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar la página.");}finally{setLoading(false);}}
  const protectedAccount=Boolean(selected&&(selected.protected||selected.id===memberId));
  return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section ref={ref} className="drawer detail-drawer" role="dialog" aria-modal="true" aria-labelledby="users-title"><div className="drawer-head"><h2 id="users-title">Usuarios y permisos</h2><button className="close" aria-label="Cerrar" onClick={close}>×</button></div><div className="detail-body">
    <p>Añade el correo con el que la persona inicia sesión. Esto asigna permisos del taller; no envía invitaciones ni concede acceso al sitio privado.</p>
    <button className="secondary-button" disabled={busy} onClick={()=>choose(null)}>Nueva cuenta</button>
    {loading&&<p role="status">Cargando usuarios…</p>}<ul className="staff-list">{page?.users.map(user=><li key={user.id}><button className="order-link" disabled={busy} onClick={()=>choose(user)}>{user.name}</button><span>{user.email} · {roleLabels[user.role]} · {user.enabled?"Activa":"Bloqueada"}{user.protected?" · Protegida":""}</span></li>)}</ul>{page?.nextCursor&&<button className="ghost-button" disabled={loading||busy} onClick={()=>void more()}>Cargar más</button>}
    <form onSubmit={save}><fieldset disabled={busy}><legend>{selected?"Editar cuenta":"Añadir cuenta"}</legend><label>Nombre<input required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Correo de acceso<input required type="email" maxLength={254} disabled={Boolean(selected)} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Rol<select disabled={protectedAccount} value={form.role} onChange={e=>setForm({...form,role:e.target.value as Role})}>{Object.entries(roleLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Acceso<select disabled={protectedAccount} value={form.enabled} onChange={e=>setForm({...form,enabled:Number(e.target.value)})}><option value={1}>Activo</option><option value={0}>Bloqueado</option></select></label>{protectedAccount&&<p className="field-hint">Esta cuenta conserva su rol y acceso para evitar bloquear la administración.</p>}<button className="primary-button" disabled={!dirty}>{busy?"Guardando…":"Guardar cuenta"}</button></fieldset></form>
    {error&&<p className="field-error" role="alert">{error}</p>}<h3>Últimos cambios de permisos</h3><ol className="history-list">{page?.audit.map(event=><li key={event.id}><p>{event.message}</p><small>{new Date(event.createdAt).toLocaleString("es-PA",{timeZone:"America/Panama"})} · {event.actorEmail}</small></li>)}</ol>
  </div></section></div>;
}
