CREATE TABLE "equipment_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "equipment_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"equipment_id" integer NOT NULL,
	"kind" text NOT NULL,
	"message" text DEFAULT '' NOT NULL,
	"from_status" text,
	"to_status" text,
	"actor_user_id" text NOT NULL,
	"actor_email" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "equipment" ADD COLUMN "estimated_exit_date" text;--> statement-breakpoint
ALTER TABLE "equipment" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_equipment_technician_entry" ON "equipment" ("assigned_technician","entry_date");--> statement-breakpoint
CREATE INDEX "idx_history_equipment_id" ON "equipment_history" ("equipment_id","id");--> statement-breakpoint
ALTER TABLE "equipment_history" ADD CONSTRAINT "equipment_history_equipment_id_equipment_id_fkey" FOREIGN KEY ("equipment_id") REFERENCES "equipment"("id");