import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const equipment = sqliteTable(
  "equipment",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    orderNumber: text("order_number").notNull().unique(),
    invoiceNumber: text("invoice_number").unique(),
    customerName: text("customer_name").notNull(),
    customerPhone: text("customer_phone").notNull().default(""),
    customerEmail: text("customer_email").notNull().default(""),
    equipmentType: text("equipment_type").notNull(),
    assignedTechnician: text("assigned_technician").notNull().default("Sin asignar"),
    brand: text("brand").notNull().default(""),
    model: text("model").notNull().default(""),
    serialNumber: text("serial_number").notNull().default(""),
    accessories: text("accessories").notNull().default(""),
    reportedIssue: text("reported_issue").notNull(),
    diagnosis: text("diagnosis").notNull().default(""),
    damageNotes: text("damage_notes").notNull().default(""),
    partsDescription: text("parts_description").notNull().default(""),
    partsCostCents: integer("parts_cost_cents").notNull().default(0),
    laborDescription: text("labor_description").notNull().default("Servicio técnico / mano de obra"),
    laborCostCents: integer("labor_cost_cents").notNull().default(0),
    status: text("status").notNull().default("ingreso"),
    entryDate: text("entry_date").notNull(),
    exitDate: text("exit_date"),
    invoiceSubtotalCents: integer("invoice_subtotal_cents"),
    invoiceTaxCents: integer("invoice_tax_cents"),
    invoiceTotalCents: integer("invoice_total_cents"),
    invoiceTaxRate: real("invoice_tax_rate"),
    warrantyDays: integer("warranty_days").notNull().default(30),
    notes: text("notes").notNull().default(""),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("idx_equipment_updated_at_id").on(table.updatedAt, table.id),
    index("idx_equipment_status").on(table.status),
    index("idx_equipment_exit_date").on(table.exitDate),
    index("idx_equipment_status_entry_date").on(table.status, table.entryDate),
    index("idx_equipment_customer_name").on(table.customerName),
  ],
);
