import { sql } from "drizzle-orm";
import { check, index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const equipment = sqliteTable(
  "equipment",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    orderNumber: text("order_number").notNull().unique(),
    invoiceNumber: text("invoice_number").unique(),
    customerName: text("customer_name").notNull(),
    customerPhone: text("customer_phone").notNull().default(""),
    customerEmail: text("customer_email").notNull().default(""),
    equipmentType: text("equipment_type").notNull(),
    assignedTechnician: text("assigned_technician").notNull().default("Sin asignar"),
    brand: text("brand").notNull().default(""),
    model: text("model").notNull().default(""),
    serialNumber: text("serial_number").notNull().default(""),
    accessories: text("accessories").notNull().default(""),
    reportedIssue: text("reported_issue").notNull(),
    diagnosis: text("diagnosis").notNull().default(""),
    damageNotes: text("damage_notes").notNull().default(""),
    partsDescription: text("parts_description").notNull().default(""),
    partsCostCents: integer("parts_cost_cents").notNull().default(0),
    laborDescription: text("labor_description").notNull().default("Servicio técnico / mano de obra"),
    laborCostCents: integer("labor_cost_cents").notNull().default(0),
    status: text("status").notNull().default("ingreso"),
    entryDate: text("entry_date").notNull(),
    exitDate: text("exit_date"),
    estimatedExitDate: text("estimated_exit_date"),
    version: integer("version").notNull().default(1),
    paidCents: integer("paid_cents").notNull().default(0),
    invoiceSubtotalCents: integer("invoice_subtotal_cents"),
    invoiceTaxCents: integer("invoice_tax_cents"),
    invoiceTotalCents: integer("invoice_total_cents"),
    invoiceTaxRate: real("invoice_tax_rate"),
    warrantyDays: integer("warranty_days").notNull().default(30),
    notes: text("notes").notNull().default(""),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("idx_equipment_updated_at_id").on(table.updatedAt, table.id),
    index("idx_equipment_status").on(table.status),
    index("idx_equipment_exit_date").on(table.exitDate),
    index("idx_equipment_status_entry_date").on(table.status, table.entryDate),
    index("idx_equipment_technician_entry").on(table.assignedTechnician, table.entryDate),
    index("idx_equipment_customer_name").on(table.customerName),
  ],
);

export const payments = sqliteTable("payments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  operationId: text("operation_id").notNull().unique(),
  equipmentId: integer("equipment_id").notNull().references(() => equipment.id),
  amountCents: integer("amount_cents").notNull(),
  method: text("method").notNull(),
  reference: text("reference").notNull().default(""),
  note: text("note").notNull(),
  reversalOf: integer("reversal_of").unique(),
  actorUserId: text("actor_user_id").notNull(),
  actorEmail: text("actor_email").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, table => [index("idx_payments_equipment").on(table.equipmentId, table.id),
  check("payment_sign", sql`(${table.amountCents} > 0 AND ${table.reversalOf} IS NULL) OR (${table.amountCents} < 0 AND ${table.reversalOf} IS NOT NULL)`)]);

// Append-only events. Original notes remain on equipment for legacy records.
export const equipmentHistory = sqliteTable("equipment_history", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  equipmentId: integer("equipment_id").notNull().references(() => equipment.id),
  kind: text("kind").notNull(),
  message: text("message").notNull().default(""),
  fromStatus: text("from_status"),
  toStatus: text("to_status"),
  actorUserId: text("actor_user_id").notNull(),
  actorEmail: text("actor_email").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, table => [index("idx_history_equipment_id").on(table.equipmentId, table.id)]);

export const inventoryItems = sqliteTable("inventory_items", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  sku: text("sku").notNull().unique(),
  name: text("name").notNull(),
  supplier: text("supplier").notNull().default(""),
  unitCostCents: integer("unit_cost_cents").notNull().default(0),
  stock: integer("stock").notNull().default(0),
  minimumStock: integer("minimum_stock").notNull().default(0),
  version: integer("version").notNull().default(1),
}, table => [check("inventory_stock_bounds", sql`${table.stock} BETWEEN 0 AND 1000000`),
  check("inventory_minimum_bounds", sql`${table.minimumStock} BETWEEN 0 AND 1000000`),
  check("inventory_cost_nonnegative", sql`${table.unitCostCents} >= 0`)]);

export const inventoryMovements = sqliteTable("inventory_movements", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  operationId: text("operation_id").notNull().unique(),
  itemId: integer("item_id").notNull().references(() => inventoryItems.id),
  equipmentId: integer("equipment_id").references(() => equipment.id),
  sourceMovementId: integer("source_movement_id"),
  kind: text("kind").notNull(),
  quantity: integer("quantity").notNull(),
  unitCostCents: integer("unit_cost_cents").notNull(),
  stockAfter: integer("stock_after").notNull(),
  note: text("note").notNull(),
  actorUserId: text("actor_user_id").notNull(),
  actorEmail: text("actor_email").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, table => [index("idx_inventory_movements_item").on(table.itemId, table.id),
  index("idx_inventory_movements_equipment").on(table.equipmentId, table.id),
  index("idx_inventory_movements_source").on(table.sourceMovementId),
  check("inventory_movement_nonzero", sql`${table.quantity} != 0`)]);
export const attachments = sqliteTable("attachments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  operationId: text("operation_id").notNull().unique(),
  equipmentId: integer("equipment_id").notNull().references(() => equipment.id),
  objectKey: text("object_key").notNull().unique(),
  filename: text("filename").notNull(),
  contentType: text("content_type").notNull(),
  size: integer("size").notNull(),
  sha256: text("sha256").notNull(),
  stage: text("stage").notNull(),
  caption: text("caption").notNull(),
  actorUserId: text("actor_user_id").notNull(),
  actorEmail: text("actor_email").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, table => [index("idx_attachments_equipment").on(table.equipmentId, table.id)]);
